adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/read/', adminapp.TraveUserListView.as_view(), name='users'),
    path('user/create/', adminapp.user_create, name='user_create'),
    path('user/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('user/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    path('countries/read/', adminapp.countries, name='countries'),
    path('countries/create/', adminapp.CountryCreateView.as_view(), name='country_create'),
    path('countries/update/<int:pk>/', adminapp.CountryUpdateView.as_view(), name='country_update'),
    path('countries/delete/<int:pk>/', adminapp.CountryDeleteView.as_view(), name='country_delete'),

    path('accomodation/read/countries/<int:pk>/', adminapp.accomodations, name='accommodations'),
    path('accomodation/update/<int:pk>/', adminapp.accomodation_update, name='accommodation_update'),
    path('accomodation/create/countries/<int:pk>/', adminapp.accomodation_create, name='accommodation_create'),
    path('accomodation/read/<int:pk>/', adminapp.AccomodationDetailView.as_view(), name='accommodation_read'),
    path('accomodation/delete/<int:pk>/', adminapp.accomodation_delete, name='accommodation_delete'),
]

authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.loguot, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:nights>/', basketapp.basket_edit, name='edit')
]

mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.accommodations, name='index'),
    path('accomodation_details/<int:pk>/', mainapp.accomodation, name='accomodation'),
]

market_prj/urls.py
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('', mainapp.main, name='main'),
    path('list_of_accommodations/', include('mainapp.urls', namespace='acc')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('order/', include('ordersapp.urls', namespace='order')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ordersapp/urls.py
from django.urls import path

import ordersapp.views as ordersapp


app_name = 'ordersapp'

urlpatterns = [
    path('', ordersapp.OderList.as_view(), name='orders_list'),
    path('create/', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
    path('update/<int:pk>/', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
    path('read/<int:pk>/', ordersapp.OrderRead.as_view(), name='order_read'),
    path('delete/<int:pk>/', ordersapp.OrderDelete.as_view(), name='order_delete'),
    path('forming/complete/<int:pk>/', ordersapp.order_forming_complete, name='order_forming_complete'),
]

mainapp/models.py
from django.db import models



class ListOfCountries(models.Model):
    name = models.CharField(verbose_name='name', max_length=64, unique=True)
    description = models.TextField(verbose_name='description', blank=True)
    is_active = models.BooleanField(verbose_name='actvie', default=True)

    def __str__(self):
        return self.name


class Regions(models.Model):
    country = models.ForeignKey(ListOfCountries, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='name', max_length=64, unique=True)
    description = models.TextField(verbose_name='description', blank=True)
    is_active = models.BooleanField(verbose_name='active', default=True)

    def __str__(self):
        return self.name


class Accommodation(models.Model):
    country = models.ForeignKey(ListOfCountries, on_delete=models.CASCADE)
    region = models.ForeignKey(Regions, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='name of residence', max_length=128, unique=True)
    image = models.ImageField(upload_to='accommodation_img', blank=True)
    short_desc = models.TextField(verbose_name='short product description', max_length=64, blank=True)
    description = models.TextField(verbose_name='product description', blank=True)
    availability = models.PositiveIntegerField(verbose_name='nomer of available rooms')
    price = models.DecimalField(verbose_name='price', max_digits=8, decimal_places=2, default=0)
    room_desc = models.TextField(verbose_name='short room description', max_length=64, blank=True)
    is_active = models.BooleanField(verbose_name='actvie', default=True)

    @staticmethod
    def get_items():
        return Accommodation.objects.filter(
            is_active=True).order_by(
                'country', 'regions', 'name'
                )
    
    def __str__(self):
        return f"{self.name} ({self.country.name})"

mainapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Accommodation, ListOfCountries

def main(request):
    return render(request, 'mainapp/index.html')



def accommodations(request):
    title = "accommadation"

    list_of_accommodations = Accommodation.objects.filter(is_active=True)

    content = {
        'title': title,
        'list_of_accommodations': list_of_accommodations,
    }

    return render(request, 'mainapp/accomodations.html', content)


def accomodation(request, pk):
    title = 'products'

    content = {
        'title': title,
        'accommodation': get_object_or_404(Accommodation, pk=pk),
    }

    return render(request, 'mainapp/accomodation_details.html', content)

mainapp/templates/mainapp/includes/inc_footer.html
<div class="page-footer font-small unique-color-dark">
    <div class="container">
        <div class="row py-4 d-flex align-items-center">    
            <div class="col-md-6 col-lg-7 text-center text-md-right">

                <!-- Facebook -->
                <a class="fb-ic">
                    <i class="fab fa-facebook-f white-text mr-4"> </i>
                </a>
                <!-- Twitter -->
                <a class="tw-ic">
                    <i class="fab fa-twitter white-text mr-4"> </i>
                </a>
                <!-- Google +-->
                <a class="gplus-ic">
                    <i class="fab fa-google-plus-g
                    white-text mr-4"> </i>
                </a>
                <!--Linkedin -->
                <a class="li-ic">
                    <i class="fab fa-linkedin-in white-text mr-4"> </i>
                </a>
                <!--Instagram-->
                <a class="ins-ic">
                    <i class="fab fa-instagram white-text"> </i>
                </a>

            </div>
        </div>
    </div>
    <div class="container text-center text-md-left mt-5">
        <div class="row mt-3">
            <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                <h6 class="text-uppercase font-weight-bold">О нас</h6>
                <hr class="deep-purple accent-2 mb-4 mt-0
                 d-inline-block mx-auto" style="width: 60px;">
                <p>Thank you for patience and understanding.</p>

            </div>
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                <h6 class="text-uppercase font-weight-bold">Страны</h6>
                <hr class="deep-black accent-2 mb-4 mt-0
                d-inline-block mx-auto" style="width: 60px;">
                <p>
                    <a href="#!">...</a>
                </p>
                <p>
                    <a href="#!">...</a>
                </p>
                <p>
                    <a href="#!">...</a>
                </p>
                <p>
                    <a href="#!">...</a>
                </p>
            </div>
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                <h6 class="text-uppercase font-weight-bold">
                    Полезные ссылки</h6>
                <hr class="deep-purple accent-2 mb-4 mt-0
                d-inline-block mx-auto" style="width: 60px;">
                <p>
                    <a href="#!">...</a>
                </p>
                <p>
                    <a href="#!">...</a>
                </p>
                <p>
                    <a href="#!">...</a>
                </p>
                <p>
                    <a href="#!">...</a>
                </p>
            </div>
            <div class="col-md-4 col-lg-3
            col-xl-3 mx-auto mb-md-0 mb-4">
                <hr class="deep-purple accent-2 mb-4 mt-0
                d-inline-block mx-auto" style="width: 60px;">
                <p>
                    <i class="fas fa-home mr-3"></i>
                    Moscow, Russia</p>
                <p>
                    <i class="fas fa-envelope mr-3"></i>
                    user@mail.ru</p>
                <p>
                    <i class="fas fa-phone mr-3"></i>
                    + 01 000 567 88</p>
                <p>
                    <i class="fas fa-print mr-3"></i>
                    + 01 000 567 89</p>
            </div>
        </div>
    </div>
    <div class="footer-copyright text-center py-3">&copy; 2020 Copyright:
        <a href="#">thereisnomercy.com</a>
    </div>
</div>

mainapp/templates/mainapp/includes/inc_menu.html
<div class="">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarTogglerDemo01"
            aria-controls="navbarTogglerDemo01" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="{% url 'main' %}">TravelMarket</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item"><a class="nav-link"
                                    href="{% url 'acc:index' %}">
                забронировать размещение</a></li>

                <li class="nav-item dropdown">
                    {% if user.is_authenticated %}
                
                        <a class="nav-link dropdown-toggle"
                           href="" data-toggle="dropdown" aria-haspopup="true"
                           aria-expanded="false">
                            {{ user|default:'пользователь' }}
                        </a>
                
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'auth:edit' %}">профиль</a>
                            <a class="dropdown-item" href="{% url 'basket:view' %}">basket</a>
                            <a class="dropdown-item" href="{% url 'order:orders_list' %}">заказы</a> 

                
                            {% if user.is_superuser %}
                                <div class="dropdown-divider"></div>
                                    <a class="dropdown-item"
                                        href="{% url 'admin:users' %}">adminka
                                    </a>
                            {% endif %}
                        </div>
                
                        <li class="nav-item">
                            <a class="nav-link" 
                               href="{% url 'auth:logout' %}">выйти</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" 
                               href="{% url 'auth:login' %}">войти</a>
                        </li>
                    {% endif %}
                </li>
        </ul>
        
        <form class="form-inline my-2 my-lg-0" >
            <input class="form-control mr-sm-1 " action="{% url 'acc:index' %}"
                   type="search" placeholder="Поиск на сайте" aria-label="Search"
            name="search">
            <button class="btn btn-outline-danger my-2 my-sm-0 disabled" 
                    type="submit">Поиск</button>
        </form>

    </div>
</nav>
</div>