adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/read/', adminapp.TraveUserListView.as_view(), name='users'),
    path('user/create/', adminapp.user_create, name='user_create'),
    path('user/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('user/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    path('countries/read/', adminapp.countries, name='countries'),
    path('countries/create/', adminapp.CountryCreateView.as_view(), name='country_create'),
    path('countries/update/<int:pk>/', adminapp.CountryUpdateView.as_view(), name='country_update'),
    path('countries/delete/<int:pk>/', adminapp.CountryDeleteView.as_view(), name='country_delete'),

    path('accomodation/read/countries/<int:pk>/', adminapp.accomodations, name='accommodations'),
    path('accomodation/update/<int:pk>/', adminapp.accomodation_update, name='accommodation_update'),
    path('accomodation/create/countries/<int:pk>/', adminapp.accomodation_create, name='accommodation_create'),
    path('accomodation/read/<int:pk>/', adminapp.AccomodationDetailView.as_view(), name='accommodation_read'),
    path('accomodation/delete/<int:pk>/', adminapp.accomodation_delete, name='accommodation_delete'),
]

authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.loguot, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

market_prj/urls.py
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('', mainapp.main, name='main'),
    path('list_of_accommodations/', include('mainapp.urls', namespace='acc')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('order/', include('ordersapp.urls', namespace='order')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms
from authapp.models import TravelUser
from authapp.forms import TravelUserEditForm
from mainapp.models import ListOfCountries, Accommodation



class TravelUserAdminEditForm(TravelUserEditForm):
    class Meta:
        model = TravelUser
        fields = '__all__'


class ListOfCountriesEditForm(forms.ModelForm):
    class Meta:
        model = ListOfCountries
        fields = '__all__'

    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'from-cotrol'
            field.help_text = ''




class AccomodationEditForm(forms.ModelForm):
    class Meta:
        model = Accommodation
        fields = '__all__'


        def __init__(self, *args, **kwargs):
            super(self).__init__(*args, **kwargs)
            for field_name, field in self.fields.items():
                field.widget.attrs['class'] = 'form-control'
                field.help_text = ''

adminapp/views.py
from django.shortcuts import get_object_or_404, HttpResponseRedirect, render
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse, reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.utils.decorators import method_decorator
from mainapp.models import Accommodation, ListOfCountries
from authapp.models import TravelUser
from authapp.forms import TravelUserRegisterForm
from adminapp.forms import TravelUserAdminEditForm, AccomodationEditForm



class TraveUserListView(ListView):
    model = TravelUser
    template_name = 'adminapp/users.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)



@user_passes_test(lambda u: u.is_superuser)
def user_create(request):
    title = 'пользователи/создание'

    if request.method == 'POST':
        user_form = TravelUserRegisterForm(request.POST, request.FILES)
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('admin:users'))
    else:
        user_form = TravelUserRegisterForm()

    content = {
        'title': title,
        'update_form': user_form,
    }

    return render(request, 'adminapp/user_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def user_update(request, pk):
    title = 'user/update'

    edit_user = get_object_or_404(TravelUser, pk=pk)

    if request.method == 'POST':
        edit_form = TravelUserAdminEditForm(
                                            request.POST,
                                            request.FILES,
                                            instance=edit_user
                                        )
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('admin:user_update', args=[edit_user.pk]))
    else:
        edit_form = TravelUserAdminEditForm(instance=edit_user)

    content = {
        'title': title,
        'update_form': edit_form,
    }

    return render(request, 'adminapp/user_update.html', content)



@user_passes_test(lambda u: u.is_superuser)
def user_delete(request, pk):
    title = 'user/delete'

    user = get_object_or_404(TravelUser, pk=pk)

    if request.method == 'POST':
        user.is_active = False
        user.save()
        return HttpResponseRedirect(reverse('admin:users'))

    content = {
        'title': title,
        'user_to_delete': user,
    }

    return render(request, 'adminapp/user_to_delete.html', content)



@user_passes_test(lambda u: u.is_superuser)
def countries(request):
    title = 'админка/страны'

    countries_list = ListOfCountries.objects.all()

    content = {
        'title': title,
        'objects': countries_list,
    }

    return render(request, 'adminapp/countries.html', content)


class CountryCreateView(CreateView):
    model = ListOfCountries
    template_name = 'adminapp/country_update.html'
    success_url = reverse_lazy('admin:countries')
    fields = '__all__'


class CountryUpdateView(UpdateView):
    model = ListOfCountries
    template_name = 'adminapp/country_update.html'
    success_url = reverse_lazy('admin:countries')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'страны/редактирование'

        return context


class CountryDeleteView(DeleteView):
    model = ListOfCountries
    template_name = 'adminapp/country_delete.html'
    success_url = reverse_lazy('admin:countries')

    def form_valid(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())





@user_passes_test(lambda u: u.is_superuser)
def accomodations(request, pk):
    title = 'админка/размещение'

    country = get_object_or_404(ListOfCountries, pk=pk)
    accommodation_list = Accommodation.objects.filter(
        country__id=pk).order_by('name')

    content = {
        'title': title,
        'country': country,
        'objects': accommodation_list,
    }

    return render(request, 'adminapp/accommodations.html', content)


@user_passes_test(lambda u: u.is_superuser)
def accomodation_create(request, pk):
    title = 'размещение/создание'
    country = get_object_or_404(ListOfCountries, pk=pk)

    if request.method == 'POST':
        accomodation_form = AccomodationEditForm(request.POST, request.FILES)

        if accomodation_form.is_valid():
            accomodation_form.save()
            return HttpResponseRedirect(reverse('admin:accommodations', args=[pk]))
    else:
        accomodation_form = AccomodationEditForm(
            initial={'country': country}
        )

    content = {
        'title': title,
        'update_form': accomodation_form,
        'country': country,
    }

    return render(request, 'adminapp/accommodation_update.html', content)



@user_passes_test(lambda u: u.is_superuser)
def accomodation_update(request, pk):
    title = 'размещение/редактирование'

    edit_accommodation = get_object_or_404(Accommodation, pk=pk)

    if request.method == 'POST':
        accomodation_edit_form = AccomodationEditForm(
            request.POST, request.FILES, instance=edit_accommodation)
        if accomodation_edit_form.is_valid():
            accomodation_edit_form.save()
            return HttpResponseRedirect(reverse('admin:accommodation_read', args=[edit_accommodation.pk]))
    else:
        accomodation_edit_form = AccomodationEditForm(
            instance=edit_accommodation
        )
    
    content = {
        'title': title,
        'update_form': accomodation_edit_form,
        'country': edit_accommodation.country,
    }

    return render(request, 'adminapp/accommodation_update.html', content)



class AccomodationDetailView(DetailView):
    model = Accommodation
    template_name = 'adminapp/accommodation_read.html'



@user_passes_test(lambda u: u.is_superuser)
def accomodation_delete(request, pk):
    title = 'размещение/удаление'
    accommodation = get_object_or_404(Accommodation, pk=pk)

    if request.method == 'POST':
        accommodation.is_active = False
        accommodation.save()
        return HttpResponseRedirect(reverse('admin:accommodations', args=[accommodation.country.pk]))

    content = {
        'title': title,
        'accommodation_to_delete': accommodation,
    }

    return render(request, 'adminapp/accommodation_delete.html', content)

adminapp/templates/adminapp/accommodation_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="user_delete">
        Уверены, что хотите удалить {{ accommodation_to_delete.username }}
        {% if accommodation_to_delete.first_name %}
                    ({{ accommodation_to_delete.first_name|title }}</b>
                    {% if accommodation_to_delete.last_name %}
                        {{ accommodation_to_delete.last_name|title }}
                    {% endif %})
                {% endif %}?
        <form action="{% url 'admin:accommodation_delete' accommodation_to_delete.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin:accommodations'
            accommodation_to_delete.country.pk%}">отмена</a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/accommodation_read.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="product_read">
        <div class="product_name">
            Предложение
            <strong>
                {{ object.name|title }}
            </strong>
        </div>
        <img src="/media/{{ object.image|default:'accommodation_img/default.jpg' }}"
             alt="{{ object.name }}">
        <div class="summary">
            <b>цена</b>
            <p>{{ object.price }} руб</p>
            <b>количество ночей</b>
            <p>{{ object.availability }}</p>
            <b>в каталоге</b>
            <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
            <p>
                <button>
                    <a href="{% url 'admin:accommodation_update' object.pk %}">
                        редактировать
                    </a>
                </button>
            </p>
            <p>
                <button>
                    <a href="{% url 'admin:accommodation_delete' object.pk %}">
                        удалить
                    </a>
                </button>
            </p>
            <p>
                <button>
                    <a href="{% url 'admin:accommodations' object.country.pk %}">
                        назад
                    </a>
                </button>
            </p>
        </div>
    <div class="product_desc">
        <b>краткая информация</b>
        <p>{{ object.short_desc }}</p>
        <br><br>
        <b>подробная информация</b>
        <p>{{ object.short_desc }}</p>
    </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/accommodation_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ update_form.as_p }}
    <input class="form_control" type="submit" value="сохранить">
    </form>

    <button class="btn btn-round form_control last">
        <a href="{% url 'admin:accommodations' country.pk %}">
            к списку предложений
        </a>
    </button>
{% endblock %}

adminapp/templates/adminapp/accommodations.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load tagz %}

{% block content %}
    <div class="products_list">
        <button class="new_product">
            <a href="{% url 'admin:accommodation_create' country.pk %}">
                новое предложение
            </a>
        </button>

        {% for object in objects %}
            <div class="product_record 
                    {% if not object.is_active %}not_active{% endif %}">
                <img
                        src="{{ object.image | media_acc }}"
                        alt="{{ object.name }}">
                <div class="product_name">
                    {{ object.name|title }}
                </div>
                <div class="product_actions">
                    <button>
                        <a href="{% url 'admin:accommodation_read' object.pk %}">
                            подробнее
                        </a>
                    </button>
                    <button>
                        <a href="{% url 'admin:accommodation_update' object.pk %}">
                            редактировать
                        </a>
                    </button>
                    <button>
                        <a href="{% url 'admin:accommodation_delete' object.pk %}">
                            удалить
                        </a>
                    </button>
                </div>
                <div class="summary">
                    <b>цена</b>
                    <p>{{ object.price }} руб</p>
                    <b>количество</b>
                    <p>{{ object.availability }}</p>
                </div>
                <div class="product_desc">
                    {{ object.short_desc|title }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
        <title>TravelMarket</title>
    {% endblock %}
    {% block css %}
        <link rel="stylesheet" type="text/css"
              href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css"
              href="{% static 'css/style.css' %}">
    {% endblock %}
    {% block js %}
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
                integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/
                zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
                crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/
        dist/umd/popper.min.js"
                integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlv
                I9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
                crossorigin="anonymous"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    {% endblock %}
</head>
<body>

<div class="admin_container">
    <div class="h2 text-center head">
        Админка
    </div>
    {% block menu %}
        <div class="admin_menu">
            {% include 'adminapp/includes/inc_menu.html' %}
        </div>
    {% endblock %}

    {% block content %}
    {% endblock %}
</div>

</body>
</html>

adminapp/templates/adminapp/countries.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="categories_list">
    <button class="new_category">
      <a href="{% url 'admin:country_create' %}">
        новая страна
      </a>
    </button>
      
    {% for object in objects %}
      <div class="category_record
 {% if not object.is_active %}not_active{% endif %}"
      
        <div class="category_name">
          {{ object.name|title }}
        </div>
        <div class="category_actions">
          <button>
            <a href="{% url 'admin:accommodations' object.pk %}">
              размещения
            </a>
          </button>
          <button>
            <a href="{% url 'admin:country_update' object.pk %}">
              редактировать
            </a>
          </button>
          <button>
            <a href="{% url 'admin:country_delete' object.pk %}">
              удалить
            </a>
          </button>
        </div>
        <div class="category_desc">
          {{ object.description|title }}
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}

adminapp/templates/adminapp/country_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="category_delete">
        Уверены, что хотите удалить страну <strong>
        {{ country_to_delete.name }}</strong>?
        <form action="{% url 'admin:country_delete' object.pk %}"
              method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin:countries' %}">отмена</a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/country_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}

    <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form_control" type="submit" value="сохранить">
    </form>
    <button class="btn btn-round form-control last">
        <a href="{% url 'admin:countries' %}">
            к списку стран
        </a>
    </button>
{% endblock %}

adminapp/templates/adminapp/user_to_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="user_delete">
        Уверены, что хотите удалить {{ user_to_delete.username }}
        {% if user_to_delete.first_name %}
                    ({{ user_to_delete.first_name|title }}</b>
                    {% if user_to_delete.last_name %}
                        {{ user_to_delete.last_name|title }}
                    {% endif %})
                {% endif %}?
        <form action="{% url 'admin:user_delete' user_to_delete.pk %}"
              method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin:users' %}">отмена</a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ update_form.as_p }}
    <input class="form_control" type="submit" value="сохранить">
    </form>

    <button class="btn btn-round form_control last">
        <a href="{% url 'admin:users' %}">
            к списку пользователей
        </a>
    </button>
{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="users_list">
    <button class="new_user">
      <a href="{% url 'admin:user_create' %}">
        новый пользователь
      </a>
    </button>
    {% for object in object_list %}
      <div 
       class="user_record {% if not object.is_active %}not_active{% endif %}">
        <img 
          src="/media/{{ object.avatar|default:'users_avatars/default.jpg' }}"
          alt="{{ object.username }}">
        <div class="user_role">
          {% if object.is_superuser %}
            администратор
          {% else %}
            пользователь
          {% endif %}
          <button>
            <a href="{% url 'admin:user_update' object.pk %}">
              редактировать
            </a>
          </button>
          <button>
            <a href="{% url 'admin:user_delete' object.pk %}">
              удалить
            </a>
          </button>
        </div>
        <div class="user_name">
          <p><strong>{{ object.username }}</strong></p>
       <p>
            {% if object.first_name %}
              <b>{{ object.first_name|title }}</b>
                {% if object.last_name %}
                  <p>{{ object.last_name|title }}</p>
                {% endif %}
            {% endif %}
        </p>
        </div>
        <div class="user_age">
          age:<br>
          {{ object.age }} лет
                   </div>
        <div class="user_email">
          email:<br>
          {{ object.email }}
        </div>
        <div class="user_lastlogin">
          logged:<br>
          {{ object.last_login }}
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}