authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.loguot, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:nights>/', basketapp.basket_edit, name='edit')
]

mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.accommodations, name='index'),
    path('accomodation_details/<int:pk>/', mainapp.accomodation, name='accomodation'),
]

market_prj/urls.py
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('', mainapp.main, name='main'),
    path('list_of_accommodations/', include('mainapp.urls', namespace='acc')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('order/', include('ordersapp.urls', namespace='order')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models



class ListOfCountries(models.Model):
    name = models.CharField(verbose_name='name', max_length=64, unique=True)
    description = models.TextField(verbose_name='description', blank=True)
    is_active = models.BooleanField(verbose_name='actvie', default=True)

    def __str__(self):
        return self.name


class Regions(models.Model):
    country = models.ForeignKey(ListOfCountries, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='name', max_length=64, unique=True)
    description = models.TextField(verbose_name='description', blank=True)
    is_active = models.BooleanField(verbose_name='active', default=True)

    def __str__(self):
        return self.name


class Accommodation(models.Model):
    country = models.ForeignKey(ListOfCountries, on_delete=models.CASCADE)
    region = models.ForeignKey(Regions, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='name of residence', max_length=128, unique=True)
    image = models.ImageField(upload_to='accommodation_img', blank=True)
    short_desc = models.TextField(verbose_name='short product description', max_length=64, blank=True)
    description = models.TextField(verbose_name='product description', blank=True)
    availability = models.PositiveIntegerField(verbose_name='nomer of available rooms')
    price = models.DecimalField(verbose_name='price', max_digits=8, decimal_places=2, default=0)
    room_desc = models.TextField(verbose_name='short room description', max_length=64, blank=True)
    is_active = models.BooleanField(verbose_name='actvie', default=True)

    @staticmethod
    def get_items():
        return Accommodation.objects.filter(
            is_active=True).order_by(
                'country', 'regions', 'name'
                )
    
    def __str__(self):
        return f"{self.name} ({self.country.name})"

mainapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Accommodation, ListOfCountries

def main(request):
    return render(request, 'mainapp/index.html')



def accommodations(request):
    title = "accommadation"

    list_of_accommodations = Accommodation.objects.filter(is_active=True)

    content = {
        'title': title,
        'list_of_accommodations': list_of_accommodations,
    }

    return render(request, 'mainapp/accomodations.html', content)


def accomodation(request, pk):
    title = 'products'

    content = {
        'title': title,
        'accommodation': get_object_or_404(Accommodation, pk=pk),
    }

    return render(request, 'mainapp/accomodation_details.html', content)

mainapp/templates/mainapp/accomodation_details.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}

    <div class="container-fluid">
        <div class="media ">
            <img src="/media/{{ accommodation.image }}" 
                 class="img-fluid mt-2 col-lg-offset-4" 
						alt="Responsive image"
                 style="height: 300px">
            <div class="ml-1 container-fluid">
                <div class="align-content-lg-between text-center">
                    <h1 class="mt-3 ml-3">
				{{ accommodation.name|title }}</h1>
                    <br>
                    <p>месторасположение: 
				{{ accommodation.region|title }}</p>
                    <br>
                    <p>стоимость за сутки: {{ accommodation.price }}</p>
                    <br><br><br><br>
                </div>
                <div class="float-right">
                    {% if user.is_authenticated %}
                    <button class="btn  btn-danger ">
                        <a style="color: white; text-decoration: none"
                           href="{% url 'basket:add' accommodation.pk %}">Забронировать</a>
                    </button>
                    {% endif %}
                </div>
            </div>

        </div>
        <div class="mt-3">
            <h3>Описание</h3>
            {{ accommodation.description|title }}
        </div>
    </div>

{% endblock %}

mainapp/templates/mainapp/accomodations.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}


    <div class="container mt-3">
        <div class="row centered">
            {% for offer in list_of_accommodations %}
                            
                <div class="card  col-lg-4" style="width: 16rem; display: flex">
                    <img src="/media/{{ offer.image }}"
                         class="card-img-top filters__img" alt="...">
                    <div class="card-body fa fa-align-justify">
                        <h5 class="card-title">{{ offer.name|title }}</h5>
                        <p class="card-text">{{ offer.region|title }}</p>
                        <p class="card-text">{{ offer.price }} за 
								сутки.</p>
                        <a href="{% url 'acc:accomodation' offer.pk %}"
                           class="btn btn-danger">Подробнее</a>
                    </div>
                </div>

            {% endfor %}
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    <title>TravelMarket</title>
    {% endblock %}
    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet"
         href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
              integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
              crossorigin="anonymous">
    {% endblock %}
    {% block js %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
                integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
                crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
                integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
                crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
                integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
                crossorigin="anonymous"></script>
    {% endblock %}
</head>
<body>
    <div class="container">
    
        {% block menu %}
            {% include 'mainapp/includes/inc_menu.html' %}
        {% endblock %}
    
        {% block list %}
    
        {% endblock %}
    
        {% block content %}
    
        {% endblock %}
    
    </div>
    </body>
    <footer>
        {% block footer %}
            {% include 'mainapp/includes/inc_footer.html' %}
        {% endblock %}
    </footer>    
</html>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
    <div class="">
        <div id="carouselExampleFade" class="carousel slide
        carousel-fade" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="{% static 'img/thai.jpg' %}"
                         class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'img/beach.jpg' %}"
                         class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'img/sands.jpg' %}"
                         class="d-block w-100" alt="...">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleFade"
               role="button" data-slide="prev">
                <span class="carousel-control-prev-icon"
                      aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next"
               href="#carouselExampleFade" role="button" data-slide="next">
                <span class="carousel-control-next-icon"
                      aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>


        <div class="card nav-item">
            <div class="card-body">
                <h5 class="card-title">Отдых,
                    который Вы заслужили</h5>
                <p class="card-text">Лучшие и самые дешёвые
                    предложения на рынке от поставщиков</p>
                <a class="btn btn-danger"
                   href="{% url 'acc:index' %}">Смотреть размещение</a>
            </div>
        </div>
    </div>
{% endblock %}